#!/usr/bin/env bash
# WSL runner for Puppet

PULL='.pull'
SUB='.submodules'

case $1 in
    clean)
        echo pull and update submodules
        rm $PULL $SUB
        ;;
    *)
        ;;
esac


find $DUMP_DIR -name $PULL -mtime +1 -delete
if [ ! -f $PULL ]; then
    echo pull latest changes
    git pull
    touch $PULL
fi

find $DUMP_DIR -name $SUB -mtime +7 -delete

PUPPET_MODULES=''

# WSL always uses Linux paths
PUPPET_MODULES=":/etc/puppetlabs/code/modules/"
if [ -e /bin/sudo ]; then
    PUPPET_INSTALL='sudo puppet module install'
    PUPPET_APPLY='sudo puppet apply -v'
fi


if [ ! -f $SUB ]; then
    echo update submodules
    ${PUPPET_INSTALL} puppetlabs-stdlib
    ${PUPPET_INSTALL} puppetlabs-vcsrepo

    touch $SUB
fi

if [[ -f ~/.keys/env ]]; then
    source ~/.keys/common_env
fi

if [[ ! -z $FACTER_SSHJ_SPEC ]]; then
    export PUPPET_APPLY="sudo FACTER_SSHJ_SPEC=${FACTER_SSHJ_SPEC} puppet apply -v"
fi

set -x
${PUPPET_APPLY} \
    --modulepath `pwd`/modules${PUPPET_MODULES} \
    manifests/hosts.pp $@
