theme = "cyber"
theme_mode = "auto"

[[panels]]
position = "top"
size = 24
left = ["workspaces-pager", "pager", "mpris"]
center = ["weather", "notifications"]
right = ["tray", "removable", "clipboard", "keyboard", "privacy", "bluetooth", "network", "brightness", "audio", "battery", "clock"]


[applets.weather]
city_name = "Minsk"

[applets.workspaces-pager]
extends = "pager"
display = "workspaces"
appearance = "labels"

[applets.notifications]
label = "{count}"
tooltip = "{count} notifications"
badge_style = "none"
popup_timeout_ms = 2500
popup_visible_limit = 1
popup_position = "top_right"
popup_margin_x = 0
popup_margin_y = 0

[idle]
enabled = true
respect_inhibitors = true

[idle.profiles.ac]
listeners = [
  { timeout = 300, on_idle = "loginctl lock-session" },
  { timeout = 600, on_idle = "niri msg action power-off-monitors" },
]

[idle.profiles.battery]
listeners = [
  { timeout = 300, on_idle = "loginctl lock-session" },
  { timeout = 600, on_idle = "niri msg action power-off-monitors" },
]
